language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - gl1776@nyu.edu
    on_success: always
    on_failure: never

    recipients:
      - ma4814@nyu.edu
    on_success: always
    on_failure: always  
